### ISSUE TITLE
[Bug] Conditional inputs disappear once selected

### ISSUE THREAD

**Issue by estallio** [docusealco/docuseal#254]
Hi,

I could not find documentation for conditions on fields so I played around a bit. I added a checkbox field and set a condition for a text field. When I opened the document, only the checkbox was visible. After checking the checkbox, the text field appeared and I could fill it out. However, when I unchecked the checkbox again, both fields, the checkbox and the text field disappeared and I had to reload the page to start the process again. I thing the expected behavior is the checkbox caused a toggle of the text field, right?

Cheers,
Leo

**Comment by omohokcoj** [comment]
@estallio the bug was caused by the last text field set as conditional field - so unchecking the checkbox removed the current field causing an error.
It has been fixed in the latest version.

**Comment by estallio** [comment]
The issue still persists. I've observed that the issue only occurs when selecting the checkbox in the PDF view. When editing the checkbox in the submission form at the bottom, the form works.
